### ISSUE TITLE
Changing locales causes page to break on specific views (Using adblocker)

### ISSUE THREAD

**Issue by Ryaaahs** [uselinked/website#4]
When changing locales on specific pages such as legal, privacy, license.
It will cause the webpage to bug out, as shown in the image.
Another side effect of this is the tab title changing to the error displayed in the screenshot

![image](https://user-images.githubusercontent.com/46785810/163074718-3e4ac9e9-fb10-46ec-a4d6-1bf8298f103e.png)

How to reproduce:
Go to either legal, privacy, license.
Change the locale.
Change the page within the footer links.
Get the error displayed the in the screenshot.
(Using an ad-blocker)

From the error, it seems to be an issue with Fathom and the use of an ad-blocker (ublock origin).
What's your thoughts on this @lostdesign ?

**Comment by lostdesign** [comment]
This simply happens on any page view as the middleware is triggered on each route. 

Basically the error needs to be caught and logged or maybe just fail silently. Gonna check with the main package to see wether optimal chaining works here.

Thanks for the report.

**Comment by lostdesign** [comment]
Can you retry?

**Comment by Ryaaahs** [comment]
> Can you retry?
Tested on my browser (Firefox Dev) using uBlock origin and didn't run into any issues! 👍

**Comment by lostdesign** [comment]
Amazing, thanks @Ryaaahs <3
